server:
  port: 8081

algafood:
  jwt:
    keystore:
      path: keystores/algafood.jks
      password: 123456
      keypair-alias: algafood

logging:
  level:
    org.springframework: DEBUG

spring:
  datasource:
    hikari:
      maximum-pool-size: 5 #maximo de conexoes
      minimum-idle: 3 # minimo de conexoes, ou seja, começa com 3
      idle-timeout: 10000 #tempo limite de ociosidade das conexoes excedentes, ou seja, 5 - 3 = 2, se essas 2 nao serem usadas em 10 seg, seram fechadas
    url: jdbc:mysql://localhost:3306/algafood?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: root
    jpa:
      properties:
        #javax.persistence.schema-generation.scripts.action: create
        #javax.persistence.schema-generation.scripts.create-target: src/main/resources/ddl.sql
        hibernate:
          dialect: org.hibernate.dialect.MySQL57Dialect
      #generate-ddl: true
      #hibernate:
      #  ddl-auto: create
      show-sql: true
